version: '3'
services:
  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
  todofront:
    image: todofrontend
    ports:
      - "3000:3000"
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
      - REACT_APP_API_PORT=3001
  todoback:
    image: todobackend
    ports:
      - "3001:3001" 